# Cloudflare Pages - rehansworld
# https://developers.cloudflare.com/pages/functions/wrangler-configuration

"$schema" = "./node_modules/wrangler/config-schema.json"
name = "rehansworld"
compatibility_date = "2026-02-23"
pages_build_output_dir = "build"

[vars]
API_KEY = "b80aac717fb9b7909d983a2fa344cc308b67b"